### ISSUE TITLE
Add "hidden property" list support

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-view#15]
Add another property to scenario:
```yaml
[root]
  - properties:
      - hiddenProperties: [String]
```
The idea is to hide some building properties that are used by the system, but not interesting for users. For example, visualization color, or some type of building id. At this moment the only property I hide is "geomId".
