### ISSUE TITLE
Add default camera position

### ISSUE THREAD

**Issue by achirkin** [achirkin/qua-view#16]
Another scenario property:
```yaml
[root]
  - properties:
      - defaultCameraFocus: [x,y,z]
      - defaultCameraViewDist: Number
      - defaultCameraViewAngles: [phi,theta]
```
`defaultCameraFocus` should be the same as underlying reference system coordinates.
Distance, probably, in meters, angles in radians.
This should affect the position loaded when user presses camera button, and also should be triggered at scenario load event.

Look at https://github.com/achirkin/qua-view/blob/master/src/Program/Model/Camera.hs#L175 to get an idea how this works
